### PR TITLE
hot fix :)

### PR DESCRIPTION
**Pull request by berkut1**

### CODE REVIEW

**Comment by berkut1** [comment]
this fix for Sublime 2

**Comment by koroshiya** [comment]
Understood. While ST2 isn't officially supported, removing a comma is simple enough.

**Comment by berkut1** [comment]
Thank you. Without this fix, ST2 just crashed :)
I next week, will move to ST3. (don't saw ST3 release)

**Comment by koroshiya** [comment]
ST3 is still in beta, and has been for a very long time. But it's stable enough if you're using a non-dev build (the latest being 3103).

**Comment by berkut1** [comment]
Ok, thank you for this information.

**Pull request merged**
